### ISSUE TITLE
build error report and work around

### ISSUE THREAD

**Issue by Ruide** [fireeye/rvmi#2]
rvmi/kvm-rvmi-kmod/external-module-compat-comm.h:

#if LINUX_VERSION_CODE < KERNEL_VERSION(4,6,0) && LINUX_VERSION_CODE > KERNEL_VERSION(4,4,0)
#define CPUID_7_ECX 16
#endif

need to be commented out for building in Linux_kernel_version between 4.6 and 4.4

Or else it will conflict with rvmi/kvm-rvmi-kmod/x86/external-module-compat.h:

enum cpuid_leafs
{
        CPUID_1_EDX             = 0,
        CPUID_8000_0001_EDX,
        CPUID_8086_0001_EDX,
        CPUID_LNX_1,
        CPUID_1_ECX,
        CPUID_C000_0001_EDX,
        CPUID_8000_0001_ECX,
        CPUID_LNX_2,
        CPUID_LNX_3,
        CPUID_7_0_EBX,
        CPUID_D_1_EAX,
        CPUID_F_0_EDX,
        CPUID_F_1_EDX,
        CPUID_8000_0008_EBX,
        CPUID_6_EAX,
        CPUID_8000_000A_EDX,
        CPUID_7_ECX,
};

compiler will say: ERROR: expected identifier before numeric constant ...

**Comment by pfohjo** [comment]
Thanks, do you want to submit a pull request?
